# Generated by Django 4.2.7 on 2023-11-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoriteapartment",
            options={
                "verbose_name": "Понравившиеся",
                "verbose_name_plural": "Понравившиеся",
            },
        ),
    ]
