# Generated by Django 4.2.7 on 2024-02-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('users', '0007_alter_favoriteapartment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='favoriteapartment',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
    ]
