# Generated by Django 4.2.7 on 2024-02-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('users', '0008_alter_comment_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
    ]
