# Generated by Django 4.2.7 on 2024-02-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_apartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='apartments',
        ),
    ]
