version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tab1k
      - POSTGRES_PASSWORD=TOBI8585
      - POSTGRES_DB=bonapart_db
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - .:/code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email tabigatkarbayev@icloud.com --agree-tos --no-eff-email --force-renewal -d bonapart.kz -d www.bonapart.kz

volumes:
  postgres_data:

