version: '3'

services:
  web:
    build: .
    container_name: bonapart
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:latest
    container_name: bonapart-db
    environment:
      POSTGRES_DB: bonapart_db
      POSTGRES_USER: tab1k
      POSTGRES_PASSWORD: TOBI8585
    networks:
      - web
    user: "postgres"

  nginx:
    image: nginx:latest
    container_name: bonapart-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"  # добавлен порт для SSL
    networks:
      - web

  certbot:
    image: certbot/certbot
    container_name: bonapart-certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  web:
    driver: bridge


