# Generated by Django 4.2.7 on 2024-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район'),
        ),
    ]
