# Generated by Django 4.2.7 on 2024-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_images/'),
        ),
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
    ]
