# Generated by Django 4.2.7 on 2024-02-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_apartment_image1_apartment_image10_apartment_image11_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentStatus',
        ),
    ]
