# Generated by Django 4.2.7 on 2024-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_apartment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='dishes',
            field=models.BooleanField(default=False, verbose_name='Посуда'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='electric_kettle',
            field=models.BooleanField(default=False, verbose_name='Электрический чайник'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='fridge',
            field=models.BooleanField(default=False, verbose_name='Холодильник'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='hygiene',
            field=models.BooleanField(default=False, verbose_name='Гигиенические принадлежности'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='mini_bar',
            field=models.BooleanField(default=False, verbose_name='Мини Бар'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='plate',
            field=models.BooleanField(default=False, verbose_name='Плита'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='shower',
            field=models.BooleanField(default=False, verbose_name='Душ'),
        ),
    ]
