# Generated by Django 4.2.7 on 2024-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0013_apartment_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="level",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="room",
            field=models.PositiveIntegerField(
                choices=[("one", "1"), ("one", "2"), ("one", "3"), ("one", "4")],
                verbose_name="Комнат",
            ),
        ),
    ]
