# Generated by Django 4.2.7 on 2024-03-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0015_remove_apartment_rating_alter_apartment_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="room",
            field=models.PositiveIntegerField(
                choices=[("one", "1"), ("two", "2"), ("three", "3"), ("four", "4")],
                verbose_name="Комнат",
            ),
        ),
    ]
