# Generated by Django 4.2.7 on 2024-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0016_alter_apartment_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="room",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                max_length=255,
                verbose_name="Комнат",
            ),
        ),
    ]
