# Generated by Django 4.2.7 on 2024-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0017_alter_apartment_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="approval_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата одобрения"
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата истечения срока годности"
            ),
        ),
    ]
