# Generated by Django 4.2.7 on 2024-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0018_apartment_approval_date_apartment_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
    ]
