# Generated by Django 4.2.7 on 2024-04-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "apartments",
            "0020_remove_apartment_image1_remove_apartment_image10_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartments.apartment",
                    ),
                ),
            ],
        ),
    ]
