# Generated by Django 4.2.6 on 2023-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Квартира", "verbose_name_plural": "Квартиры"},
        ),
        migrations.AddField(
            model_name="apartment",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lux", "Люкс"),
                    ("business", "Бизнес"),
                    ("prestige", "Престиж"),
                ],
                max_length=10,
                null=True,
                verbose_name="Класс квартиры",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="air_conditioning",
            field=models.BooleanField(default=False, verbose_name="Кондиционер"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="bath",
            field=models.BooleanField(default=False, verbose_name="Ванна"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="capacity",
            field=models.PositiveIntegerField(default=2, verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="description",
            field=models.TextField(verbose_name="Подробнее"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="doublebeds",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Двухспальных мест"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="elevator",
            field=models.BooleanField(default=True, verbose_name="Лифт"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="floor",
            field=models.PositiveIntegerField(default=5, verbose_name="Этаж"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="hairdryer",
            field=models.BooleanField(default=False, verbose_name="Фен"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="iron",
            field=models.BooleanField(default=False, verbose_name="Утюг"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="name",
            field=models.CharField(max_length=355, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="orthopedic_mattress",
            field=models.BooleanField(
                default=False, verbose_name="Ортопедический матрац"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="parking",
            field=models.BooleanField(default=False, verbose_name="Платный паркинг"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="room",
            field=models.PositiveIntegerField(default=1, verbose_name="Комнат"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="singlebeds",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Односпальных мест"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="smart_tv",
            field=models.BooleanField(default=False, verbose_name="Smart TV"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="square",
            field=models.PositiveIntegerField(default=37, verbose_name="Площадь"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="total_floors",
            field=models.PositiveSmallIntegerField(verbose_name="Кол-во этажей"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="washing_machine",
            field=models.BooleanField(default=False, verbose_name="Стиральная машинка"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="wifi",
            field=models.BooleanField(default=False, verbose_name="Wi-Fi"),
        ),
    ]
