# Generated by Django 4.2.6 on 2023-10-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_apartment_address_alter_apartment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="apartment_images/")),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Фотографии",
                        to="website.apartment",
                    ),
                ),
            ],
        ),
    ]
