# Generated by Django 4.2.6 on 2023-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_apartmentimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Брэнд")),
                ("model", models.CharField(max_length=255, verbose_name="Модель")),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("minimal", "Минимальная"),
                            ("average", "Средняя"),
                            ("full", "Полная"),
                        ],
                        max_length=15,
                        verbose_name="Комплектация",
                    ),
                ),
                ("volume", models.FloatField(verbose_name="Объем")),
                ("day", models.SmallIntegerField(verbose_name="Время")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
            },
        ),
        migrations.AlterModelOptions(
            name="apartmentimage",
            options={
                "verbose_name": "Фотография квартиры",
                "verbose_name_plural": "Фотографии квартир",
            },
        ),
    ]
