# Generated by Django 4.2.6 on 2023-10-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_car_alter_apartmentimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Фотография"
            ),
        ),
    ]
