# Generated by Django 4.2.6 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_car_capacity_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedan", "Седан"),
                    ("universal", "Универсал"),
                    ("hatchback", "Хэтчбек"),
                    ("crossover", "Кроссовер"),
                    ("jeep", "Внедорожник"),
                    ("limousine", "Лимузин"),
                ],
                max_length=15,
                null=True,
                verbose_name="Кузов",
            ),
        ),
    ]
