# Generated by Django 4.2.6 on 2023-10-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_apartment_image1_apartment_image2_apartment_image3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Широта"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Долгота"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.apartment",
                        verbose_name="ЖК",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геопозиция дома",
                "verbose_name_plural": "Геопозиции домов",
            },
        ),
    ]
