# Generated by Django 4.2.6 on 2023-10-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="latitude",
            new_name="discount_count",
        ),
    ]
