# Generated by Django 4.2.6 on 2023-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_rename_latitude_discount_discount_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Скидка"),
        ),
    ]
