# Generated by Django 4.2.6 on 2023-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_alter_discount_discount_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("comfort", "Комфорт"), ("business", "Бизнес")],
                max_length=10,
                null=True,
                verbose_name="Класс машины",
            ),
        ),
    ]
