# Generated by Django 4.2.6 on 2023-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_car_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 звезда"),
                    (2, "2 звезды"),
                    (3, "3 звезды"),
                    (4, "4 звезды"),
                    (5, "5 звезд"),
                ],
                null=True,
            ),
        ),
    ]
