# Generated by Django 4.2.6 on 2023-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_remove_reservation_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ala", "Алматинский"),
                    ("bai", "Байконурский"),
                    ("esil", "Есильский"),
                    ("nurin", "Нуринский"),
                    ("sary", "Сарыаркинский"),
                ],
                max_length=10,
                null=True,
                verbose_name="Район",
            ),
        ),
    ]
