# Generated by Django 4.2.6 on 2023-11-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.AddField(
            model_name="stock",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="stock_images"),
        ),
    ]
