# Generated by Django 4.2.7 on 2023-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_stock_link_alter_reservation_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geoposition",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="geoposition",
            name="longitude",
        ),
        migrations.AddField(
            model_name="geoposition",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geoposition",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="geo_images"),
        ),
    ]
