# Generated by Django 4.2.7 on 2024-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_comment_apartment_and_more'),
        ('website', '0026_apartment_deal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='geoposition',
            name='apartment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='GeoPosition',
        ),
    ]
